declare const styles: {
  readonly pageHeader: string;
  readonly pageHeaderLeft: string;
  readonly pageTitleDivider: string;
  readonly pageTitleBlock: string;
  readonly pageTitle: string;
  readonly pageDescription: string;
  readonly pageTabContainer: string;
  readonly pageTabList: string;
  readonly pageTabItem: string;
  readonly pageTabItemLabel: string;
  readonly pageTabItemActive: string;
  readonly pageTabItemUnderline: string;
  readonly pageHeaderHelp: string;
  readonly pageHeaderHelpIcon: string;
  readonly pageHeaderHelpText: string;
  readonly pageContent: string;
  readonly toolbar: string;
  readonly segmentedTab: string;
  readonly segmentedTabItem: string;
  readonly segmentedTabItemActive: string;
  readonly paginationBar: string;
};
export default styles;
